---
default_stages: [pre-commit]

default_language_version:
  python: python3.10

ci:
  skip: [commitlint]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
        name: check for debug statements
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-no-eval
      - id: python-use-type-annotations
        name: check that python type annotations not comments
  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        name: check python docstrings
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        name: sort python imports
        args: [--select, I, --fix]
      - id: ruff-format
        name: format python
      - id: ruff
        name: check python
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.48.0
    hooks:
      - id: markdownlint
        name: check markdown
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.38.0
    hooks:
      - id: yamllint
        name: check yaml
        args: [--format, parsable, --strict]
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.24.0
    hooks:
      - id: commitlint
        name: check commit
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional"]
