---
name: CI

"on":
  push:
  pull_request:

jobs:
  pre-commit:
    name: ✨️ ️Pre-commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Use Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1

  test:
    name: 🧪 Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Cache pip
        uses: actions/cache@v5
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Use Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"
      - name: Install pytest
        run: pip install -U pytest==7.1.2
      - name: Run tests
        run: pytest --doctest-modules --no-header --no-summary
