---
name: CI

on:  # yamllint disable-line rule:truthy
  push:
  pull_request:

jobs:
  pre-commit:
    name: ✨️ ️Pre-commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Use Python
        uses: actions/setup-python@v2
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0

  test:
    name: 🧪 Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Use Python
        uses: actions/setup-python@v2
      - name: Install pytest
        run: pip install -U pytest==7.1.2
      - name: Run tests
        run: pytest --doctest-modules --no-header --no-summary
